export const SLUGS: Record<string, string> = {
  'Cerf élaphe': 'cerf-elaphe',
  'Chevreuil': 'chevreuil',
  'Sanglier': 'sanglier',
  'Chamois': 'chamois',
  'Mouflon méditerranéen': 'mouflon-mediterraneen',
  "Lièvre d'Europe": 'lievre-europe',
  'Lapin de garenne': 'lapin-garenne',
  'Perdrix rouge': 'perdrix-rouge',
  'Perdrix grise': 'perdrix-grise',
  'Faisan commun': 'faisan-commun',
  'Canard colvert': 'canard-colvert',
  'Bécasse des bois': 'becasse-bois',
  'Grive draine': 'grive-draine',
  'Pigeon ramier': 'pigeon-ramier',
  'Caille des blés': 'caille-bles',
  'Tétras-lyre': 'tetras-lyre',
  'Lagopède alpin': 'lagopede-alpin',
  'Perdrix bartavelle': 'perdrix-bartavelle',
  'Tangue': 'tangue',
  'Lièvre à collier noir': 'lievre-collier-noir',
  'Cerf de Java': 'cerf-de-java',
};
